CC = clang
# Without POSIX, fdopen not included
C_VERSION = gnu23
AR = llvm-ar
PROJECT = psakill
DEBUG_FLAGS = -g -O0
CFLAGS = $DEBUG_FLAGS \
				-std=$C_VERSION \
				-Wall -Werror -Wextra -Wpedantic \
				-I$PWD
LDFLAGS = -lcurses
DEPFILES = `{/bin/sh -c 'find . -maxdepth 1 -name "*.d"'}

all:V: $PROJECT.exe compile_commands.json

$PROJECT.exe: main.o parse.o
	$CC $CFLAGS $LDFLAGS \
		$prereq -o $target

<|cat $DEPFILES /dev/null

compile_commands.json: mkfile
	mk clean
	bear -- mk "${PROJECT}.exe"

%.o: %.c
  $CC $CFLAGS \
    -MT $target -MMD -MP -MF $stem.d \
    -c $stem.c -o $target

clean:V:
	rm -rf *.exe *.o *.a *.d compile_commands.json

# vim: ft=make
