CC = bear --append -- clang
C_VERSION = c23
AR = llvm-ar
PROJECT = flooboo
DEBUG_FLAGS = -g -O0 -DNDEBUG
WARNING_FLAGS = -Wall -Werror -Wextra -Wpedantic
CFLAGS = $DEBUG_FLAGS \
				-std=$C_VERSION \
				$WARNING_FLAGS \
				-I$PWD/include
LDFLAGS =
DEPFILES = `{/bin/sh -c 'find . -name "*.d"'}
LIB_OBJECTS = lib/buffer.o \
							lib/lexer.o \
							lib/parser.o

run:V: $PROJECT.exe
	"./${PROJECT}.exe"

<|cat $DEPFILES /dev/null

$PROJECT.exe: bin/main.o lib/lib$PROJECT.a
	$CC $LDFLAGS $prereq -o $target

bin/%.o: bin/%.c
	$CC $CFLAGS \
		-MT $target -MMD -MP -MF bin/$stem.d \
		-c bin/$stem.c -o $target

lib/%.o: lib/%.c
	$CC $CFLAGS \
		-MT $target -MMD -MP -MF lib/$stem.d \
		-c lib/$stem.c -o $target

lib/lib$PROJECT.a: $LIB_OBJECTS
	$AR rcs $target $prereq

clean:V:
	rm -rf *.exe *.d *.o *.a compile_commands.json
	(cd bin && rm -f *.d *.o *.a)
	(cd lib && rm -f *.d *.o *.a)

# vim: ft=make
