DEPFILES = `{/bin/sh -c 'find . -maxdepth 1 -name "*.d"'}

<|cat $DEPFILES /dev/null

lib$PROJECT.a: mod1.o
	$AR rcs $target $prereq

%.o: %.c
  $CC $CFLAGS \
    -MT $target -MMD -MP -MF $stem.d \
    -c $stem.c -o $target

clean:V:
  rm -rf *.a *.o *.d
